name: 'ESP-IDF Project Build'

on:
  workflow_dispatch:  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        ref: 'dev'
        submodules: 'recursive'
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: latest
        target: esp32-c6
   

    - name: Archive build output artifacts
      uses: actions/upload-artifact@v3
      with:
       name: build
       path: |
         build/bootloader/bootloader.bin
         build/partition_table/partition-table.bin
         build/ota_data_initial.bin
         build/storage.bin
         build/${{ github.event.repository.name }}.bin
