name: 'ESP-IDF Project Build'

on:
  workflow_dispatch:  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        ref: 'dev'
        submodules: 'recursive'
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: latest
        target: esp32-c6
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
       name: built_files
       path: binaries/
