name: 'ESP-IDF Project Build'

on:
  workflow_dispatch:  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        ref: 'dev'
        submodules: 'recursive'
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: latest
        target: esp32-c6
      
    - name: Attach artifact
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: |
          /build/MEEF.bin
          /build/partition_table/partition-table.bin 
          /build/bootloader/bootloader.bin 
          /build/storage.bin
          /build/ota_data_initial.bin 
